openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /create-account:
    post:
      summary: A resource for generating greetings
      operationId: postCreateAccount
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /payments:
    post:
      operationId: postPayments
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /transactions:
    get:
      operationId: getTransactions
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
  /registered-funding-banks:
    get:
      operationId: getRegisteredFundingBanks
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /accounts:
    get:
      operationId: getAccounts
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
